# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
