# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170712_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
