# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170719_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_status',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[(b'succeeded', b'Succeeded'), (b'pending', b'Pending'), (b'failed', b'Failed'), (b'cancelled', b'Cancelled'), (b'refunded', b'Refunded')], max_length=50),
        ),
    ]
