# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20170719_2248'),
    ]

    operations = [
    ]
