# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20170721_2054'),
        ('payments', '0004_auto_20170721_2242'),
    ]

    operations = [
    ]
