# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20170721_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract'),
        ),
    ]
