# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_merge_20170721_2042'),
        ('payments', '0005_merge_20170724_0522'),
        ('payments', '0005_auto_20170721_2222'),
    ]

    operations = [
    ]
