# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merge_20170723_2256'),
        ('payments', '0005_merge_20170724_0522'),
    ]

    operations = [
    ]
