# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20170724_1836'),
        ('payments', '0006_merge_20170724_0650'),
    ]

    operations = [
    ]
