# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=30)),
                ('issuer', models.CharField(max_length=30)),
                ('indicated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('extend_id', models.CharField(max_length=60, null=True)),
                ('trial_date', models.DateTimeField()),
                ('trial_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContractNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract')),
            ],
        ),
    ]
