# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20170711_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='extend_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
