# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20170712_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractnotes',
            options={'verbose_name_plural': 'contract notes'},
        ),
        migrations.AlterField(
            model_name='contractnotes',
            name='text',
            field=models.TextField(),
        ),
    ]
