# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='issuer_email',
            field=models.EmailField(default='missing@missing.missing', max_length=254),
            preserve_default=False,
        ),
    ]
