# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20170721_2221'),
        ('contracts', '0005_contract_status'),
        ('contracts', '0005_auto_20170721_2042'),
    ]

    operations = [
    ]
