# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_merge_20170724_1836'),
        ('contracts', '0006_contract_issuer_email'),
    ]

    operations = [
    ]
