# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_merge_20170725_0034'),
        ('contracts', '0007_merge_20170725_0033'),
    ]

    operations = [
    ]
