# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_carrier', models.CharField(choices=[('@sms.wirefree.informe.ca', 'Aliant'), ('@txt.bellmobility.ca', 'Bell Mobility'), ('@sms.fido.ca', 'Fido'), ('@msg.telus.com', 'Telus'), ('@sms.lynxmobility.com', 'Lynx Mobility'), ('@text.mtsmobility.com', 'MTS Mobility'), ('@mobiletxt.ca', 'PC Telecom'), ('@sms.sasktel.com', 'SaskTel'), ('@vmobile.ca', 'Virgin Mobile'), ('@t.westnet.ca', 'Westnet'), ('@txt.windmobile.ca', 'Wind Mobile'), ('@sms.rogers.com', 'Rogers Wireless'), ('@msg.telus.com', 'Telus Mobility')], max_length=30, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('executioner', models.BooleanField(default=False)),
                ('pie_bearer', models.BooleanField(default=False)),
                ('bard', models.BooleanField(default=False)),
                ('inquisitor', models.BooleanField(default=False)),
                ('counselor', models.BooleanField(default=False)),
                ('undertaker', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('role', models.CharField(choices=[('executioner', 'Executioner'), ('pie_bearer', 'Pie Bearer'), ('bard', 'Bard'), ('inquisitor', 'Inquisitor'), ('counselor', 'Counselor'), ('undertaker', 'Undertaker')], max_length=15)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers.Volunteer')),
            ],
        ),
    ]
