# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone_carrier',
            field=models.CharField(blank=True, choices=[('@sms.wirefree.informe.ca', 'Aliant'), ('@txt.bellmobility.ca', 'Bell Mobility'), ('@sms.fido.ca', 'Fido'), ('@msg.telus.com', 'Telus'), ('@sms.lynxmobility.com', 'Lynx Mobility'), ('@text.mtsmobility.com', 'MTS Mobility'), ('@mobiletxt.ca', 'PC Telecom'), ('@sms.sasktel.com', 'SaskTel'), ('@vmobile.ca', 'Virgin Mobile'), ('@t.westnet.ca', 'Westnet'), ('@txt.windmobile.ca', 'Wind Mobile'), ('@sms.rogers.com', 'Rogers Wireless'), ('@msg.telus.com', 'Telus Mobility')], max_length=30),
        ),
    ]
