# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_auto_20170712_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
